version: '3.9'


services:
  todoapp-db:
    image: postgres:${TODOAPP_DB_VERSION}
    environment:
      POSTGRES_DB: ${TODOAPP_DB_NAME}
      POSTGRES_USER: ${TODOAPP_DB_USER}
      POSTGRES_PASSWORD: ${TODOAPP_DB_PASSWORD}
    volumes:
      - todoapp-db-data:/var/lib/postgresql/data
    networks:
      - todoapp-network
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 3s

  tokens-db:
    image: redis:alpine
    command: redis-server --requirepass ${TOKENS_DB_PASSWORD}
    environment:
      - TOKENS_DB_PASSWORD
    volumes:
      - tokens-db-data:/data
    networks:
      - todoapp-network
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", 'redis-cli -a "$$TOKENS_DB_PASSWORD" PING | grep PONG' ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 2s


volumes:
  todoapp-db-data:
  tokens-db-data:


networks:
  todoapp-network:
    driver: bridge
