-- liquibase formatted sql

-- changeset eastnetic:1684060697-1
create table users
(
    id              bigint generated by default as identity not null,
    email           varchar(255)                            not null,
    first_name      varchar(255)                            not null,
    last_name       varchar(255)                            not null,
    hashed_password varchar(255)                            not null,
    created_at      timestamp without time zone             not null,
    updated_at      timestamp without time zone             not null,
    constraint pk_users primary key (id)
);
