DROP TABLE IF EXISTS ROLES;


create table roles
(
    id              bigint generated by default as identity not null,
    name           varchar(255)                            not null,
    constraint pk_roles primary key (id)
);