-- liquibase formatted sql

-- changeset eastnetic:1684145626-1
create table todos
(
    id          bigint generated by default as identity not null,
    created_at  timestamp without time zone             not null,
    updated_at  timestamp without time zone,
    "name"      varchar(255)                            not null,
    description varchar(255),
    due_date    timestamp without time zone,
    status      varchar(255)                            not null,
    user_id     bigint                                  not null,
    constraint pk_todos primary key (id)
);

-- changeset eastnetic:1684145626-2
alter table todos
    add constraint fk_todos_on_user foreign key (user_id) references users (id);