-- liquibase formatted sql

-- changeset eastnetic:1784560897-2
DROP TABLE IF EXISTS menu;
CREATE TABLE menu (
    id              bigint generated by default as identity not null,
    name           varchar(255) not null,
    url           varchar(255) not null,
    position bigint not null,
    feature_id bigint,
    active_url BOOLEAN not null,
    parent_id bigint references menu(id),
    created_at      timestamp without time zone             not null,
    updated_at      timestamp without time zone             not null,
    constraint pk_menu primary key (id),
    CONSTRAINT uq_menu_name UNIQUE (name),
    CONSTRAINT uq_menu_feature UNIQUE (feature_id)
);